### ISSUE TITLE
Future version 0.15.0 causes error with pypy

### ISSUE THREAD

**Issue by mtimm** [datacenter/cobra#102]
With future version 0.15.0 if you do the following in pypy you get an error:

```
from future import standard_library
standard_library.install_aliases()
```

The error is:

```
tests/mit/test_session_CertSession.py:15: in <module>
standard_library.install_aliases()
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/standard_library/__init__.py:465: in install_aliases
from future.backports.urllib import request
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/backports/urllib/request.py:97: in <module>
from future.backports.http import client as http_client
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/backports/http/client.py:76: in <module>
from future.backports.email import parser as email_parser
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/backports/email/parser.py:15: in <module>
from future.backports.email.feedparser import FeedParser, BytesFeedParser
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/backports/email/feedparser.py:32: in <module>
from future.backports.email import message
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/backports/email/message.py:20: in <module>
from future.backports.email import utils
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/backports/email/utils.py:40: in <module>
from future.backports.urllib.parse import quote as url_quote, unquote as url_unquote
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/backports/urllib/parse.py:633: in <module>
_ALWAYS_SAFE_BYTES = bytes(_ALWAYS_SAFE)
../../../../../build_ve/python/pypy/site-packages/future-0.15.0-py2.7.egg/future/types/newbytes.py:108: in __new__
raise ValueError('bytes must be in range(0, 256)')
E ValueError: bytes must be in range(0, 256)
```

These errors come from the tests.

This is easy to recreate with pypy version 2.5.0 and future version 0.15.0.  This is 0.14.3:

```
$ python
Python 2.7.8 (10f1b29a2bd2, Feb 02 2015, 21:22:55)
[PyPy 2.5.0 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> from future import standard_library
>>>> standard_library.install_aliases()
>>>> exit()
```

This is 0.15.0:

```
$ python
Python 2.7.8 (10f1b29a2bd2, Feb 02 2015, 21:22:55)
[PyPy 2.5.0 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> from future import standard_library
>>>> standard_library.install_aliases()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/standard_library/__init__.py", line 465, in install_aliases
    from future.backports.urllib import request
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/backports/urllib/request.py", line 97, in <module>
    from future.backports.http import client as http_client
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/backports/http/client.py", line 76, in <module>
    from future.backports.email import parser as email_parser
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/backports/email/parser.py", line 15, in <module>
    from future.backports.email.feedparser import FeedParser, BytesFeedParser
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/backports/email/feedparser.py", line 32, in <module>
    from future.backports.email import message
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/backports/email/message.py", line 20, in <module>
    from future.backports.email import utils
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/backports/email/utils.py", line 40, in <module>
    from future.backports.urllib.parse import quote as url_quote, unquote as url_unquote
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/backports/urllib/parse.py", line 633, in <module>
    _ALWAYS_SAFE_BYTES = bytes(_ALWAYS_SAFE)
  File "/Users/mtimm/.virtualenvs/test_pypy2/site-packages/future/types/newbytes.py", line 108, in __new__
    raise ValueError('bytes must be in range(0, 256)')
ValueError: bytes must be in range(0, 256)
>>>> exit()
```

I added a bit of debugging and found that this code is hit initially when processing individual characters in an integer then when it tries to process:

```
frozenset(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '_', '.', '-'])
```

It attempts to do a char('A') and fails in this manner only on Pypy, it works fine in both python2 and python3.

**Comment by mtimm** [comment]
Moving to chore now that the workaround is in both master and develop.  Still need to resolve the overall issue which may be an upstream issue in future.

**Comment by mtimm** [comment]
This is a hint of this:  http://python-future.org/faq.html?highlight=pypy#do-you-support-pypy

> Do you support Pypy?
> Yes, except for the standard library import hooks (currently). Feedback and pull requests are welcome!
