### ISSUE TITLE
Need better handling of redirect from http to https

### ISSUE THREAD

**Issue by mtimm** [datacenter/cobra#56]
This is how things worked before ACI shipped to customers, we need to verify that this is still happening
in this manner and find a solution:

Currently http to https redirect for POST goes to GET and headers (like APIC-Request-Signature=) get dropped.  

http://docs.python-requests.org/en/latest/user/quickstart/#redirection-and-history

Maybe add something related to this to accessimpl and abstract it into the AbstractSession?  

With http being disabled by default and https being the default, I suspect many customers are simply going to enable http with a redirect to https and not worry about any man in the middle attacks with APIC being in the datacenter.

**Comment by mtimm** [comment]
More information:

When http is redirected to https, cobra throws the following error:

```
>>> from cobra.mit.access import MoDirectory
>>> from cobra.mit.session import LoginSession
>>> session = LoginSession('http://10.1.1.7', 'admin', 'ins3965!', secure=False)
>>> modir = MoDirectory(session)
>>> modir.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/insieme/cobra/cobra/mit/access.py", line 39, in login
    self._accessImpl.login()
  File "/local/insieme/cobra/cobra/internal/rest/accessimpl.py", line 134, in login
    loginHandler.login(self._session)
  File "/local/insieme/cobra/cobra/internal/rest/accessimpl.py", line 88, in login
    session._parseResponse(rsp)
  File "/local/insieme/cobra/cobra/mit/session.py", line 272, in _parseResponse
    raise LoginError(errorCode, reasonStr)
cobra.mit.session.LoginError: Failed to parse login request
>>> 
```

**Comment by mtimm** [comment]
The problem here is that requests is not carrying forward the payload.  So you get a valid POST to the http server and a reply that it has moved permanently with a location pointing to https.  The requests module then tries the https URL but does not carry forward the POST data because it is using a GET which is what browsers do.

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.1.1.7
send: '**POST** /api/aaaLogin.json HTTP/1.1\r\nHost: 10.1.1.7\r\nContent-Length: 65\r\nCookie: APIC-cookie=None\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.3.0 CPython/2.7.9rc1 Darwin/13.4.0\r\n\r\n**{"aaaUser": {"attributes": {"name": "admin", "pwd": "pas$word"}}}'**
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Server: nginx/1.6.2
header: Date: Thu, 19 Mar 2015 00:15:39 GMT
header: Content-Type: text/html
header: Content-Length: 184
header: Connection: keep-alive
header: Location: https://10.1.1.7/api/aaaLogin.json
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/aaaLogin.json HTTP/1.1" 301 184
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 10.1.1.7
send: '**GET** /api/aaaLogin.json HTTP/1.1\r\nHost: 10.1.1.7\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.3.0 CPython/2.7.9rc1 Darwin/13.4.0\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Server: nginx/1.6.2
header: Date: Thu, 19 Mar 2015 00:15:39 GMT
header: Content-Type: application/json
header: Content-Length: 108
header: Connection: keep-alive
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/aaaLogin.json HTTP/1.1" 400 108
```
