### ISSUE TITLE
MoDirectory.reauth() is no longer working.

### ISSUE THREAD

**Issue by mtimm** [datacenter/cobra#72]
After the last rounds of refactoring, calling MoDirectory.reauth() produces the following error:

```
>>> modir.reauth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mtimm/.virtualenvs/test_python2/lib/python2.7/site-packages/acicobra-0.1-py2.7.egg/cobra/mit/access.py", line 60, in reauth
    self._session.refreshSession()
AttributeError: 'LoginSession' object has no attribute 'refreshSession'
>>> exit()
```

**Comment by mtimm** [comment]
`MoDirectory.reauth()` calls `AbstractSession.refreshSession()` which no longer exists, it has been changed to `AbstractSession.refresh()`.  So two things are needed:
1.  Fix the issue.
2.  Introduce tests that exercise `AbstractSession.refresh()` via `MoDirectory.reauth()`
